dist: xenial
language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - gcc-5-alpha-linux-gnu

script:
    - ./install_dependencies.sh
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest --verbose --test-timeout 10 --output-on-failure -O ../testing_log
    - make coverage

notifications:
  slack: riceeclipse:HVcYx7InaxdEFzQHaatd1UiH
