dist: xenial
language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake

script:
    - ./install_dependencies.sh
    - mkdir build
    - cd build
    - cmake ..
    - make
    # TODO have a way to autorun all tests
    - cd test/config
    - ./config_test

notifications:
  slack: riceeclipse:gkom2AO57EGZmxU2wWPEtyR2
